apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: he6pnxqwy-go-gitops
  description: This is GitOps manifest for he6pnxqwy-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=he6pnxqwy-go
    backstage.io/kubernetes-id: he6pnxqwy-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: he6pnxqwy-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:he6pnxqwy-go
