apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: he6pnxqwy-go
  janus-idp.io/tekton: he6pnxqwy-go
  backstage.io/kubernetes-id: he6pnxqwy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: he6pnxqwy-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
